import type { Metadata } from "next";
import { Toaster } from "sonner";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AgGridRegistry from "@/lib/ag-grid-registry";
import DashboardShell from "@/components/DashboardShell";
import { ThemeProvider } from "@/components/ThemeProvider";
import { LanguageProvider } from "@/context/LanguageContext";
import { cookies } from "next/headers";
import { getPeopleCount } from "@/app/actions/getPeopleCount";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const tenantId = cookieStore.get("tenant_id")?.value;
  const peopleCount = tenantId ? await getPeopleCount(tenantId) : 0;

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <LanguageProvider>
            <AgGridRegistry />
            <DashboardShell currentTenantId={tenantId} peopleCount={peopleCount}>
              {children}
            </DashboardShell>
            <Toaster position="top-right" theme="system" />
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
