import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AgGridRegistry from "@/lib/ag-grid-registry";
import Sidebar from "@/components/Sidebar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { LanguageProvider } from "@/context/LanguageContext";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <LanguageProvider>
          <AgGridRegistry />
          <div className="flex min-h-screen bg-slate-950">
            <Sidebar />
            {/* Use margin-start (ms-64) for RTL support instead of ml-64 */}
            <main className="flex-1 ms-64 p-8 relative overflow-hidden transition-all duration-300">
              {/* Background blobs for premium feel */}
              <div className="absolute top-0 right-0 -mr-20 -mt-20 w-96 h-96 bg-brand-primary/10 rounded-full blur-[120px] pointer-events-none" />
              <div className="absolute bottom-0 left-0 -ml-20 -mb-20 w-96 h-96 bg-brand-secondary/10 rounded-full blur-[120px] pointer-events-none" />

              <div className="relative z-10">
                {children}
              </div>
            </main>
          </div>
        </LanguageProvider>
      </body>

    </html>
  );
}
